### PR TITLE
Improvements on Text Overlay

### LINKED ISSUE #2: 字型不對
參考 https://twitter.com/wenli/status/960782384521035776/photo/1

### PR DESCRIPTION
**Pull request by Edditoria**
First of all

技術性調整

This PR improves the text on IFC-roof meme.

Looked at the original video, the text overlay is actually consistent. The date and time are **full-width text**.

It was common practice in the old day: It was difficult to keep consistent on Chinese, English, punctuations and number. It was difficult to manage for editing team using different machines. Therefore, just kept it simple.

In this case, the editor may be lazy. The text spacing was too low. I bet he just resize the text overlay, and then aligned both line of text in Premier with one-click. (This was another common mistake. I saw that many times in local agency house)

The second line, location, is simply an indention. Nothing special.

----

So, I made a few improvements:

- Update npm packages, except jQuery. I hope I didn't make mistake in Webpack config.
- Combine date and time into one `<div>`. Convert text of date and time to full width.
- The space between date and time: Add a space if hour is less than 10. It does not apply to date tho, because I personally think it will be too complicated.
- Location keeps half-width English characters un-change. Because users can type more things.
- Letter-spacing is not perfect (-0.4px is better). It is to keep the second line readable, especially some locations in English.
- Add AM. We can jump off the roof in morning, right?
- Fix a few bugs, e.g. offset error on downloaded image, 12:00 am instead of 0:00 am.
- Footer and a few things in code-style.

Feel free to discuss. :pizza:

Resolves #2

### CODE REVIEW

**Comment by ShawTim** [comment]
​interesting, sorry for missing this PR for days. i completely forgot about this project :D 
will take a look and appreciate your PR.

**Comment by ShawTim** [comment]
first of all appreciate for the effort. there are some tech debt indeed i needed to resolve but i hadnt.

for the font, modern effort is actually too smooth, comparing with the old one.
original one:
image
current one:
image
suggested one:
image

i did spend a little bit effort to make it looks like the original one.
the position, the width and height, the font, blablabla.
if the original font is a mess, then i follow it as a mess, LOL. so personally i think the current font looks similar than the original one.
*but actually nobody knows becoz nobody will compare*

what do you think @Edditoria ? it's a project for fun. feel free.

**Comment by Edditoria** [comment]
Hi,

Agree that the fonts is still "too smooth". Let me share how I made decision in this series of commits:

1. Memories > shape/smoothness/etc.
1. It has to be serif font, in contrast of the san-serif that has been widely adapted in this decade. Avoid san-serif to make a distance.
1. The head of "6" and the tail of "5" are magically important. The shape is super old.
1. The word "香港" is the most important. Choose a font close enough, especially the part "氵". Energy!
1. Smoothness here is all about resolution. To be honest, I still have no idea. May be some kind of CSS filtering, or scale down-and-up using JPEG? I don't know.

Other things are relatively not important. In addition, I didn't take care the transform scale and shadow, because it is not efficient in current stage. Also, font weight is not perfect (The problem is letter-spacing for English characters. Thicker/fatter characters will make "location" unreadable)

Btw, I just can't accept the colon, sorry XDDD

----

Um... wait... Seems we have different outcome?! This is how it looks like in my Windows machine: ([link](https://github.com/Edditoria/ifc-roof/blob/master/docs/intro.png))

intro

I tried in Chrome on Mac and Firefox on Windows 10. On my Mac, Chrome cannot display DejaVu Serif. So I append LiSong Pro in the list of font-family. I assume iOS can display it properly? Not sure.

**Comment by ShawTim** [comment]
ya the tail is important.
looks like the font issue on different browser in different OS again. mine is Ubuntu Firefox.
your screenshot looks much better than what i have in my machine.

or, maybe i dont have LiSong Pro installed. do you want to embed the font (~13Mb)? or any webfont available?

**Comment by Edditoria** [comment]
Um... You are right. Font issue is a big problem. Headache!

I would make up a summary:

- OS fonts are not consistent across devices:
  - LiSong Pro doesn't match in full-width fonts and **some HK words** in macOS and iOS.
  - Best font is "DFKai-sb" (標楷體) in Windows OS, but users trend to create the meme in mobile.
  - "DFKai-sb" as main font-family and web fonts as fallback: Font width and spacing are not controllable (in different devices).
- Experience are vary if users customize their browser settings, e.g. my Chrome and Safari in the same MacBook.
- So, I won't rely on system fonts anymore. We should try the best to find a good serif font on web. (See the above comment for reasons).
- I think Google web fonts are fast and supports more characters. See the comparison in my [codepen demo][codepen_demo].
  - There may be a chance to use "邨" that is important word in Hong Kong, meanwhile I guess people will forgive inconsistency in foul languages. Therefore, I choose "Google 仿宋體" over "Google 標楷體".
  - "Google 明體" is good too. Font weight is closer, but font width is not. And I personally think it is too shape.

No matter what font you use, the best `letter-spacing` is -2px for English characters in "location". It creates more limitations.

My test env: macOS, Win 10 and Android; Chrome and Firefox; 3Mbps bandwidth.

[codepen_demo]: https://codepen.io/Edditoria/details/abvozaP

**Comment by Edditoria** [comment]
I didn't test in iOS devices. Hopefully the web fonts can solve the problems.

There may be some further improvements such as shadow and inline grow to make the font-face thinner. 😄

**Comment by ShawTim** [comment]
image
it brings the Chinese font to another level...
while it differs from the original font on TV, it's still the right style on that time i think.
is the font shown on my screen same as yours, i.e. this is what you expected?
if yes then let's just get it merged.

**Comment by Edditoria** [comment]
Yes. It is consistent now.

Have pushed 2 commits as follow up. I think it is ready to merge. Yay~

**Comment by ShawTim** [comment]
mergedddddddddddddddd

**Pull request merged**
